backend:
  name: github
  branch: main
  repo: alianza/portfolio-v2
  preview_context: alianza/portfolio-v2
  identity_url: "https://wonderful-roentgen-f3230c.netlify.app/.netlify/identity"
  gateway_url: "https://wonderful-roentgen-f3230c.netlify.app/.netlify/git"

local_backend: ${CMS_LOCAL_BACKEND:-false}
site_url: https://jwvbremen.nl/
display_url: https://jwvbremen.nl/
media_folder: public/assets
public_folder: /assets
publish_mode: editorial_workflow
logo_url: https://jwvbremen.nl/admin/cms_img.jpg

collections:
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "config"
        label: "Site Config"
        file: "content/config.json"
        description: "General site settings"
        fields:
          - { label: "Site heading", name: "siteHeading", widget: "string" }
          - { label: "Site title", name: "siteTitle", widget: "string", hint: "The title of the site (Also tab bar)" }
          - { label: "Site description", name: "siteDescription", widget: "text", hint: "Used for meta description" }
          - label: "Online accounts"
            name: "accounts"
            label_singular: "Online account"
            widget: "list"
            summary: "{{fields.name}}"
            fields:
              - { label: "Social media name", name: "name", widget: "string" }
              - { label: "Url", name: "url", widget: "string" }
              - { label: "Icon", name: "icon", widget: "image", required: false }
          - label: 'Introductions'
            name: 'introductions'
            label_singular: 'Introduction'
            widget: 'list'
            allow_add: false
            min: 3
            max: 3
            summary: '{{fields.title}}'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Media', name: 'media', widget: 'file' }
              - { label: 'Fallback Media', name: 'fallbackMedia', widget: 'file', required: false }
              - { label: 'Body', name: 'body', widget: 'markdown', editor_components: ['years-since-date'] }

  - label: 'Projects'
    name: 'projects'
    label_singular: 'Project'
    folder: 'content/projects'
    create: true
    slug: '{{startDate}}_{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Start Date', name: 'startDate', widget: 'datetime', format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: 'End Date', name: 'endDate', widget: 'datetime', format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false, required: false, default: "", hint: "Leave empty if still working (present)" }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Type', name: 'type', widget: 'select', options: ['Personal', 'Professional', "Academic"], default: 'Professional', required: false }
      - { label: 'Description', name: 'description', widget: 'text', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
